name: Build and Deploy Marp Slides

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: Build slides
        run: |
          mkdir -p dist
          for file in docs/*.md; do
            if [ -f "$file" ]; then
              filename=$(basename "$file" .md)
              marp "$file" -o "dist/${filename}.html" --html
              marp "$file" -o "dist/${filename}.pdf" --allow-local-files
            fi
          done

      - name: Create index page
        run: |
          cat > dist/index.html << 'INDEXEOF'
          <!DOCTYPE html>
          <html lang="ja">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Marp Slides</title>
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
                max-width: 800px;
                margin: 50px auto;
                padding: 20px;
                line-height: 1.6;
              }
              h1 {
                border-bottom: 2px solid #333;
                padding-bottom: 10px;
              }
              ul {
                list-style: none;
                padding: 0;
              }
              li {
                margin: 15px 0;
                padding: 15px;
                background: #f5f5f5;
                border-radius: 5px;
              }
              a {
                color: #0366d6;
                text-decoration: none;
                margin-right: 15px;
              }
              a:hover {
                text-decoration: underline;
              }
            </style>
          </head>
          <body>
            <h1>Marp Slides</h1>
            <ul>
          INDEXEOF
          
          for file in docs/*.md; do
            if [ -f "$file" ]; then
              filename=$(basename "$file" .md)
              title=$(grep -m 1 "^# " "$file" | sed 's/^# //' || echo "$filename")
              echo "      <li>" >> dist/index.html
              echo "        <strong>$title</strong><br>" >> dist/index.html
              echo "        <a href=\"${filename}.html\">HTML</a>" >> dist/index.html
              echo "        <a href=\"${filename}.pdf\">PDF</a>" >> dist/index.html
              echo "      </li>" >> dist/index.html
            fi
          done
          
          cat >> dist/index.html << 'INDEXEOF'
            </ul>
          </body>
          </html>
          INDEXEOF

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
